job_name = predict_update
universe = vanilla
executable = /condor_data/sgmcart3/condortools/condortools/helper_files/python_submit.bat
transfer_input_files = input$(PROCESS).json, $(python_file), /opt1/condor/apps/python/python_3.7.4.zip, /opt1/condor/apps/matlab/index.exe, /opt1/condor/apps/matlab/unindex.exe
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
request_cpus = 1
requirements = (Arch=="X86_64") && (OpSys=="WINDOWS")
initialdir = /condor_data/sgmcart3/condortools/tests/jobs/$(job_name)
logdir = logs
output = $(logdir)/$(job_name)/log.$(cluster).log
notification = never
python_file = predict_update.py
transfer_output_files = output$(PROCESS).json
#log file added automatically
log = /condor_data/log_temp/sgmcart3_nc_Tue_11_Feb_22:36:32_GMT_2020
queue 2

